language: node_js
node_js:
  - "10"
install: true
script: true
deploy: 
  provider: script
  skip_cleanup: true
  script: 
  - echo "no deploy"
  on:
    branch: master
after_deploy:
  - sh sh/cdn.sh
