language: node_js
node_js:
  - "10"
install: true
script: true
addons:
  ssh_known_hosts: ubuntu.zkl2333.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_61d4610c1f56_key -iv $encrypted_61d4610c1f56_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -t ubuntu@ubuntu.zkl2333.com < deploy.sh
  on:
    branch: master
